// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package vn.zalopay.zas.account.protobuf;

public interface AccountQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zas.protobuf.AccountQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
