// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package vn.zalopay.zas.account.protobuf;

public interface AccountUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zas.protobuf.AccountUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string dob = 4;</code>
   */
  java.lang.String getDob();
  /**
   * <code>string dob = 4;</code>
   */
  com.google.protobuf.ByteString
      getDobBytes();
}
