// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package vn.zalopay.zas.account.protobuf;

public interface AccountQueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zas.protobuf.AccountQueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 errorCode = 1;</code>
   */
  long getErrorCode();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.zas.protobuf.Account account = 3;</code>
   */
  boolean hasAccount();
  /**
   * <code>.zas.protobuf.Account account = 3;</code>
   */
  vn.zalopay.zas.account.protobuf.Account getAccount();
  /**
   * <code>.zas.protobuf.Account account = 3;</code>
   */
  vn.zalopay.zas.account.protobuf.AccountOrBuilder getAccountOrBuilder();
}
